meteor add accounts-password@=1.1.18
meteor add aldeed:autoform@=5.8.1
meteor add aldeed:autoform-select2@=2.0.2
meteor add aldeed:collection2@=2.9.1
meteor add aldeed:simple-schema@=1.5.3
meteor add aldeed:template-extension@=3.4.3
meteor add blaze-html-templates@=1.0.4
meteor add check
meteor add dburles:stringify-pretty
meteor add ecmascript
meteor add es5-shim
meteor add facts
meteor add gildaspk:autoform-materialize
meteor add http
meteor add ian:accounts-ui-bootstrap-3
meteor add iron:router@=1.0.13
meteor add jquery@=1.11.8
meteor add maazlik:highcharts@=0.4.0
meteor add materialize:materialize@=0.97.5
meteor add mizzao:bootboxjs
meteor add mizzao:jquery-ui
meteor add mobile-experience
meteor add momentjs:moment@=2.13.1
meteor add natestrauser:select2@=3.5.1
meteor add session
meteor add standard-minifier-css
meteor add standard-minifier-js
meteor add twbs:bootstrap@=3.3.6
meteor add zimme:select2-bootstrap3-css@=1.4.6

