meteor add accounts-base
meteor add accounts-password
meteor remove accounts-ui
meteor add aldeed:autoform
meteor add aldeed:collection2
meteor add aldeed:simple-schema
meteor add aldeed:template-extension
meteor add blaze-html-templates
meteor add check
meteor add comerc:autoform-selectize
meteor add dburles:stringify-pretty
meteor add ecmascript
meteor add es5-shim
meteor add facts
meteor add gildaspk:autoform-materialize
meteor add http
meteor add ian:accounts-ui-bootstrap-3
meteor add iron:router
meteor add jquery
meteor add maazalik:highcharts
meteor add materialize:materialize
meteor add mdg:validation-error
meteor add mizzao:bootboxjs
meteor add mizzao:build-fetcher
meteor add mizzao:jquery-ui
meteor add momentjs:moment
meteor add reactive-var
meteor add session
meteor add standard-minifier-css
meteor add standard-minifier-js
meteor add tracker
meteor add twbs:bootstrap
